# Generated by Django 3.1.2 on 2021-08-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210818_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='ab.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
