# Generated by Django 3.1.2 on 2021-08-20 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcenters',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='trainingcenters',
            name='params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=8),
        ),
    ]
